<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <RootNamespace>TaskbarBatteryMeter</RootNamespace>
    <AssemblyName>TaskbarBatteryMeter</AssemblyName>
    <ApplicationIcon>Images\PluggedIn.ico</ApplicationIcon>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskbarCore\TaskbarCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\PluggedIn.ico" />
    <Resource Include="Images\Battery.ico" />
  </ItemGroup>

</Project>
